### ISSUE TITLE
Error: Image given has not completed loading

### ISSUE THREAD

**Issue by alxhrck** [SteveMcGrath/DoFler#13]
> /opt/DoFler/node_modules/nude/nude.js:93
>                   ctx.drawImage(img, 0, 0);
>                       ^
> Error: Image given has not completed loading
>     at Error (native)
>     at /opt/DoFler/node_modules/nude/nude.js:93:9
>     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:446:3)

**Comment by SteveMcGrath** [comment]
yes, the nude.js code seems to break on partial images.  I'm actually working on dockerizing all of dofler and implementing a better NSFW filter.  in the meantime, I would recommend that you pull from https://github.com/SteveMcGrath/DoFler/tree/5e6e688c128c7f87d6fdd39abb4c618e40a9c8ed
