### ISSUE TITLE
Problem with the new release.

### ISSUE THREAD

**Issue by madmantm** [SteveMcGrath/DoFler#7]
Hi Steve, i'm having another issue, were the main portal loads, but i can't see the admin panel anymore and i get this python error below.

I tried this one on different distros again.  (Ubuntu, Fedora)

![screen shot 2015-02-22 at 3 55 27 pm](https://cloud.githubusercontent.com/assets/806561/6320436/4e639274-baab-11e4-9e07-f863c8ef2168.png)

Traceback (most recent call last):
  File "/usr/local/bin/bottle.py", line 862, in _handle
    return route.call(**args)
  File "/usr/local/bin/bottle.py", line 1732, in wrapper
    rv = callback(*a, **ka)
  File "/usr/local/lib/python2.7/dist-packages/bottle_sqlalchemy.py", line 143, in wrapper
    rv = callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/dofler/api/view.py", line 126, in get_pvs_data
    }, verify=False)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 88, in post
    return request('post', url, data=data, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 456, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 559, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 375, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPSConnectionPool(host='127.0.0.1', port=8835): Max retries exceeded with url: /login (Caused by <class 'socket.error'>: [Errno 111] Connection refused)

Thanks for your help.

**Comment by SteveMcGrath** [comment]
Let me build a lab box and test this.

**Comment by SteveMcGrath** [comment]
Aaah, this is in relation to the pvs.  in a terminal type `dofler set web_pvs_enabled 0` and then refresh the browser.  you should not get the error anymore.  I need to disable that by default ;)

**Comment by SteveMcGrath** [comment]
Note: I just pushed 4.2.2 with the necessary changes as well.  if you want to take advantage of it, just delete the settings.db file in /var/lib/dofler and upgrade the package.

**Comment by madmantm** [comment]
Thanks ! Great product by the way, i created a small shell script to copy
the bd when it's clean and replace it when i'm done.

This would be a great feature to add.

:)

On Mon, Feb 23, 2015 at 10:43 PM, Steven McGrath <notifications@github.com>
wrote:

> Note: I just pushed 4.2.2 with the necessary changes as well. if you want
> to take advantage of it, just delete the settings.db file in
> /var/lib/dofler and upgrade the package.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/SteveMcGrath/DoFler/issues/7#issuecomment-75694546>.
>



-- 
Marc-André Meloche

**Comment by SteveMcGrath** [comment]
If you have any intention of using this in a permanent capacity, I would highly recommend you move this over to a mysql (or similar) database.  The SQLite DB is really intended for small installs and to aide in getting this running on things like a pwnpad.
