### ISSUE TITLE
/image in post.py issue

### ISSUE THREAD

**Issue by ThisIsNotTheUserYouAreLookingFor** [SteveMcGrath/DoFler#8]
The exception statement of the /image post method contains an image constructor without the md5sum .this throws a python error, and doesn't save the image to the database. 

This should solve it:
except:
            image = Image(int(time.time()), 
                          request.forms.get('filetype'),
                          filedata,md5sum
            )
            db.add(image)

**Comment by SteveMcGrath** [comment]
This is no longer relevant as the codebase no longer uses python
